import {request} from './api.js';
import './assistant.css';
export function initAssistant(){
  const toggle=document.createElement('button');toggle.id='ai-fab';toggle.className='btn btn-p';toggle.setAttribute('aria-label','פתיחת עוזר בטיחות');toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<span aria-hidden="true">✦</span> עוזר SMAI';
  const dialog=document.createElement('dialog');dialog.className='sentinel-assistant';
  dialog.innerHTML=`<header><div class="assistant-brand"><span class="assistant-orb" aria-hidden="true"></span><div><strong>SMAI AI</strong><p data-assistant-mode>מתחבר למערכת…</p></div></div><button type="button" class="iconbtn" aria-label="סגירה">✕</button></header><div class="assistant-messages" aria-live="polite"><div class="assistant-message model assistant-welcome"><span class="assistant-avatar" aria-hidden="true">✦</span><div><strong>היי, אני עוזר הבטיחות של SMAI.</strong><p>ספרו לי מה קרה ואעזור לבחור את הצעד הבטוח הבא. אין לשלוח סיסמאות או קודי אימות.</p></div></div><div class="assistant-suggestions"><button type="button">פרצו לי לחשבון</button><button type="button">מישהו מטריד אותי</button><button type="button">איך שומרים ראיות?</button></div></div><section class="assistant-privacy" hidden><strong>לפני שממשיכים</strong><p>התשובה תופק בעזרת שירות AI חיצוני. אל תשלחו סיסמאות, קודי אימות או מידע מזהה.</p><button type="button" class="btn btn-p">הבנתי, אפשר להמשיך</button></section><form><label class="sr-only" for="assistant-input">הודעה לעוזר</label><div class="assistant-composer"><textarea id="assistant-input" rows="1" maxlength="6000" required placeholder="כתבו הודעה…" aria-describedby="assistant-hint"></textarea><button class="assistant-send" type="submit" aria-label="שליחת הודעה">➤</button></div><div class="assistant-form-meta"><span id="assistant-hint">Enter לשליחה · Shift+Enter לשורה חדשה</span><span>אל תשתפו סודות</span></div><p class="assistant-error" role="alert"></p></form>`;
  document.body.append(toggle,dialog);
  const close=dialog.querySelector('header>.iconbtn'),messages=dialog.querySelector('.assistant-messages'),input=dialog.querySelector('textarea'),form=dialog.querySelector('form'),error=dialog.querySelector('[role=alert]'),button=form.querySelector('.assistant-send'),privacy=dialog.querySelector('.assistant-privacy'),privacyButton=privacy.querySelector('button');
  let aiMode='basic',externalApproved=false;
  toggle.onclick=()=>{dialog.showModal();toggle.setAttribute('aria-expanded','true');setTimeout(()=>input.focus(),80);};close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{toggle.setAttribute('aria-expanded','false');toggle.focus();});
  request('/api/status').then(status=>{aiMode=status.aiMode||'basic';dialog.querySelector('[data-assistant-mode]').textContent='מערכת ההכוונה פעילה';if(aiMode==='gemini'){privacy.hidden=false;input.disabled=true;button.disabled=true;}}).catch(()=>{dialog.querySelector('[data-assistant-mode]').textContent='מערכת ההכוונה זמינה';});
  privacyButton.onclick=()=>{externalApproved=true;privacy.hidden=true;input.disabled=false;button.disabled=false;input.focus();};
  const history=[],scroll=()=>{messages.scrollTop=messages.scrollHeight;};
  const add=(text,kind)=>{const row=document.createElement('div');row.className='assistant-message '+kind;const bubble=document.createElement('div');bubble.textContent=text;if(kind==='model'){const avatar=document.createElement('span');avatar.className='assistant-avatar';avatar.setAttribute('aria-hidden','true');avatar.textContent='✦';row.append(avatar);}row.append(bubble);messages.append(row);scroll();};
  const typing=()=>{const row=document.createElement('div');row.className='assistant-message model assistant-typing';row.setAttribute('aria-label','מערכת ה-AI מקלידה');row.innerHTML='<span class="assistant-avatar" aria-hidden="true">✦</span><div><i></i><i></i><i></i><small>מקליד…</small></div>';messages.append(row);scroll();return row;};
  const resize=()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,132)+'px';};input.addEventListener('input',resize);input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();form.requestSubmit();}});
  dialog.querySelectorAll('.assistant-suggestions button').forEach(chip=>chip.onclick=()=>{input.value=chip.textContent;resize();form.requestSubmit();dialog.querySelector('.assistant-suggestions')?.remove();});
  form.onsubmit=async event=>{event.preventDefault();if(!input.value.trim()||button.disabled)return;if(aiMode==='gemini'&&!externalApproved){privacy.hidden=false;privacyButton.focus();return;}const prompt=input.value.trim();button.disabled=true;error.textContent='';add(prompt,'user');input.value='';resize();dialog.querySelector('.assistant-suggestions')?.remove();const indicator=typing();try{const result=await request('/api/ai','POST',{prompt,history,consent:externalApproved});indicator.remove();add(result.text,'model');history.push({role:'user',text:prompt},{role:'model',text:result.text});}catch(e){indicator.remove();error.textContent=e.message||'החיבור לעוזר לא הושלם. נסו שוב בעוד רגע.';}finally{button.disabled=false;input.focus();}};
}
