import {request} from './api.js';
export function renderDaily(app,{user,esc,onCleanup}){
 const key='smai_daily_v1_'+user.id;
 let state={tasks:[],checks:[]};try{const data=JSON.parse(localStorage.getItem(key)||'null');if(data&&Array.isArray(data.tasks)&&Array.isArray(data.checks))state=data;}catch{}
 let remaining=25*60,end=null,timer;
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(state));}catch{app.querySelector('#dailyStatus').textContent='אין מקום לשמירה במכשיר. אפשר לייצא את הרשימה.';}};
 app.innerHTML=`<header class="page-h"><span class="eyebrow">SMAI EVERYDAY</span><h1>קצת סדר. יותר שקט.</h1><p>משימות, זמן ריכוז והרגלי אבטחה — במקום אחד.</p><p class="daily-note">הכלים חינמיים. הרשימות נשמרות בדפדפן הזה, בנפרד לכל חשבון; הטיימר פועל כל עוד העמוד פתוח.</p></header><div class="daily-grid"><section><h2>מה עושים היום?</h2><form id="dailyAdd"><label for="dailyText">משימה חדשה</label><input id="dailyText" type="text" maxlength="180" placeholder="למשל: לסיים את העבודה" required><button class="btn btn-p" type="submit">הוספה</button></form><div id="dailyTasks"></div><button class="btn btn-g" id="dailyExport">הורדת הרשימה</button></section><section><h2>זמן ריכוז</h2><p>בחרו מקטע, התמקדו בדבר אחד ותנו מקום להפסקה.</p><label for="focusDuration">משך המקטע</label><select id="focusDuration"><option value="1500">25 דקות ריכוז</option><option value="3000">50 דקות ריכוז</option><option value="300">5 דקות הפסקה</option></select><div class="focus-clock" id="focusClock" role="timer">25:00</div><div class="row"><button class="btn btn-p" id="focusStart">התחלה</button><button class="btn btn-g" id="focusReset">איפוס</button></div><p id="focusStatus" role="status"></p></section><section><h2>בדיקת אבטחה אישית</h2><p>רשימה אישית למעקב — אינה סריקה אוטומטית של החשבונות.</p>${['הפעלתי אימות דו־שלבי בחשבונות החשובים','לכל חשבון יש סיסמה ייחודית','בדקתי מכשירים מחוברים והרשאות','שמרתי קודי שחזור במקום בטוח','בדקתי למי הפרופיל והפרטים שלי גלויים'].map((text,i)=>`<label class="daily-check"><input type="checkbox" data-security="${i}" ${state.checks.includes(i)?'checked':''}><span>${text}</span></label>`).join('')}<a class="btn btn-g" href="/account">להגדרות החשבון</a></section></div><p id="dailyStatus" role="status"></p><section class="premium-roadmap"><h2>בהמשך: מרחב עבודה משודרג</h2><p>סנכרון בין מכשירים, תזכורות ומשימות משותפות מתוכננים לחבילה עתידית. הם עדיין לא זמינים ולא נגבה עבורם תשלום.</p><a class="btn btn-g" href="/improve">איזה כלי חסר לכם?</a></section>`;
 const paint=()=>{app.querySelector('#dailyTasks').innerHTML=state.tasks.length?state.tasks.map(task=>`<div class="daily-task ${task.done?'done':''}"><input type="checkbox" data-task="${esc(task.id)}" aria-label="סימון משימה כהושלמה" ${task.done?'checked':''}><span>${esc(task.text)}</span><button class="iconbtn" data-delete="${esc(task.id)}" aria-label="מחיקת משימה">×</button></div>`).join(''):'<p class="daily-note">הוסיפו את הדבר הראשון שתרצו לסיים.</p>';};paint();
 app.querySelector('#dailyAdd').onsubmit=e=>{e.preventDefault();const input=app.querySelector('#dailyText'),text=input.value.trim();if(!text)return;if(state.tasks.length>=100){app.querySelector('#dailyStatus').textContent='אפשר לשמור עד 100 משימות. מחקו משימות שהסתיימו.';return;}state.tasks.push({id:crypto.randomUUID(),text,done:false});input.value='';save();paint();};
 app.querySelector('#dailyTasks').onclick=e=>{const id=e.target.dataset.delete;if(id){state.tasks=state.tasks.filter(task=>task.id!==id);save();paint();}};
 app.querySelector('#dailyTasks').onchange=e=>{const task=state.tasks.find(task=>task.id===e.target.dataset.task);if(task){task.done=e.target.checked;save();paint();}};
 app.querySelectorAll('[data-security]').forEach(input=>input.onchange=()=>{state.checks=[...app.querySelectorAll('[data-security]:checked')].map(x=>Number(x.dataset.security));save();});
 const tick=()=>{if(end){remaining=Math.max(0,Math.ceil((end-Date.now())/1000));if(!remaining){end=null;app.querySelector('#focusStatus').textContent='המקטע הסתיים. זמן לעצור ולנשום.';app.querySelector('#focusStart').textContent='התחלה';}}app.querySelector('#focusClock').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');};
 const reset=()=>{end=null;remaining=Number(app.querySelector('#focusDuration').value);app.querySelector('#focusStart').textContent='התחלה';app.querySelector('#focusStatus').textContent='';tick();};
 app.querySelector('#focusStart').onclick=e=>{if(end){tick();end=null;e.target.textContent='המשך';}else{if(!remaining)remaining=Number(app.querySelector('#focusDuration').value);end=Date.now()+remaining*1000;e.target.textContent='השהיה';}tick();};
 app.querySelector('#focusReset').onclick=reset;app.querySelector('#focusDuration').onchange=reset;
 timer=setInterval(tick,1000);onCleanup(()=>clearInterval(timer));
 app.querySelector('#dailyExport').onclick=()=>{const text=state.tasks.map(t=>`${t.done?'[✓]':'[ ]'} ${t.text}`).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='smai-tasks.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
}
export async function renderSupport(app,{user,esc,toast}){
 app.innerHTML='<p role="status">טוען…</p>';
 try{
  const data=await request('/api/donations');
  app.innerHTML=`<section class="donation-panel"><span class="eyebrow">SUPPORT SMAI</span><h1>עוזרים לנו להמשיך.</h1><p>רוצים לתמוך ביוזמה? אפשר לתרום דרך עמוד התשלום הרשמי שהיוצר הגדיר.</p>${data.url?`<a class="btn btn-p" href="${esc(data.url)}" target="_blank" rel="noopener noreferrer">${esc(data.label)}</a><p class="daily-note">התשלום מתבצע באתר חיצוני. בדקו שם את הסכום והאם מדובר בתרומה חד־פעמית או חוזרת לפני האישור.</p>`:'<p class="callout c-info">אפשרות התרומה תיפתח לאחר חיבור שירות התשלום. כרגע לא ניתן להעביר כאן כסף.</p>'}<p class="daily-note">תרומה אינה רכישת מנוי או הבטחה לשירות עתידי.</p>${user?.isOwner||user?.rank==='founder'?`<form id="donationSettings"><h2>הגדרת תרומות · ליוצר בלבד</h2><label>קישור תשלום ציבורי<input id="donationUrl" type="url" placeholder="https://paypal.me/…" value="${esc(data.url)}"></label><p class="daily-note">PayPal, Stripe, Ko-fi או Buy Me a Coffee. השאירו ריק כדי לכבות תרומות.</p><label>כיתוב הכפתור<input id="donationLabel" maxlength="80" value="${esc(data.label)}"></label><button class="btn btn-p">שמירת הקישור</button><p id="donationStatus" role="status"></p></form>`:''}</section>`;
  const form=app.querySelector('#donationSettings');if(form)form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await request('/api/donations','POST',{url:app.querySelector('#donationUrl').value.trim(),label:app.querySelector('#donationLabel').value.trim()});toast('קישור התרומות נשמר');await renderSupport(app,{user,esc,toast});}catch(error){app.querySelector('#donationStatus').textContent=error.message;button.disabled=false;}};
 }catch(error){app.innerHTML=`<p role="alert">${esc(error.message)}</p><a href="/support">ניסיון נוסף</a>`;}
}
