export function renderHome(app, {ic, esc, Auth, DEPTS}) {
  app.innerHTML = `<div class="sentinel-home">
  <div class="home-top anim-up"><div><div class="eyebrow">מרכז ההגנה שלך ברשת</div><h1>${Auth.user ? `שלום, ${esc((Auth.user.name || 'ברוך הבא').split(' ')[0])}` : 'טוב שהגעת. אנחנו כאן בשבילך.'}</h1><p>דיווח, הכוונה וליווי. הכל במקום אחד.</p></div><span class="system-pill"><i></i> SMAI / SENTINEL</span></div>
  <div class="mission-grid">
    <section class="mission anim-up d1"><div class="section-code">01 / YOUR DIGITAL SAFETY</div><h2>העולם דיגיטלי.<br>ההגנה <span>אישית.</span></h2><p>הטרדה, פריצה או משהו שלא מרגיש נכון? לא צריך להתמודד לבד. מתחילים בצעד קטן, ומבינים יחד מה לעשות.</p><div class="mission-actions"><a class="btn btn-p btn-lg" href="/report">${ic('plus',18)} פתיחת דיווח</a><a class="btn btn-g btn-lg" href="/track">מעקב פנייה ${ic('arrow',17)}</a></div><div class="mission-bottom"><span>${ic('lock',14)} אפשר להשתמש בכינוי</span><span>${ic('heart',14)} לילדים, לנוער ולהורים</span></div></section>
    <form class="card start-report anim-up d2" id="quick-report"><div class="card-h"><span class="ico-tile i-brand">${ic('message',19)}</span><div><h2>מה קרה ברשת?</h2><span class="small mute">אפשר להתחיל במילים שלך.</span></div></div><label class="sr-only" for="quick-description">תיאור ראשוני של המקרה</label><textarea id="quick-description" maxlength="4000" placeholder="מישהו מטריד אותי, פרצו לי לחשבון, אני דואג לילד שלי…"></textarea><button type="submit" class="btn btn-p btn-block">ממשיכים לדיווח ${ic('arrow',17)}</button><p class="hint">הטקסט יעבור לטופס. שום דיווח לא נשלח לפני האישור שלך.</p></form>
  </div>
  <div class="shortcut-row anim-up d3">${[['book','מדריכים לבטיחות ברשת','צעדים מעשיים להגנה על החשבון','articles'],['message','קהילת SMAI','מקום לשאלות, לשיתוף ולתמיכה','community'],[Auth.isStaff()?'shield':'file',Auth.isStaff()?'מרכז השליטה':'הפניות שלי',Auth.isStaff()?'פניות, צוות ומצב המערכת':'כל העדכונים על הפניות שלך',Auth.isStaff()?'admin':'my']].map(([i,t,d,p])=>`<a class="shortcut" href="/${p}"><span class="ico-tile i-brand">${ic(i,20)}</span><div><strong>${t}</strong><small>${d}</small></div>${ic('chevron',16)}</a>`).join('')}</div>
  <div class="home-bottom"><section class="card anim-up d3"><div class="panel-heading"><h2>במה אפשר לעזור?</h2><span>SUPPORT AREAS / 06</span></div>${DEPTS.map((d,i)=>`<a href="/report" class="department-row"><span class="ico-tile i-${d.cls}">${ic(d.ico,18)}</span><div><strong>${esc(d.short)}</strong><p>${esc(d.desc)}</p></div><span class="dept-n">0${i+1}</span></a>`).join('')}</section><section class="card anim-up d4"><div class="panel-heading"><h2>מרגע הדיווח, יש דרך.</h2><span>THE PROCESS</span></div><ol class="journey"><li><h3>מספרים מה קרה</h3><p>בוחרים פלטפורמה ומתארים את המקרה. אפשר להשתמש בכינוי ; הפנייה משויכת לחשבון שלכם.</p></li><li><h3>הפנייה מגיעה למקום הנכון</h3><p>המערכת מסווגת את הפנייה ומסמנת סימני דחיפות לבדיקת הצוות.</p></li><li><h3>נשארים בקשר</h3><p>מקבלים קוד מעקב לצפייה בעדכונים ולהתכתבות על הפנייה.</p></li></ol><div class="callout c-info" style="margin-top:23px"><span>${ic('info',19)}</span><div class="small">בסכנה מיידית פונים למשטרה בטלפון <a href="tel:100">100</a>. האתר אינו מוקד חירום.</div></div><a href="/articles" class="btn btn-g btn-block" style="margin-top:20px">איך מגנים על החשבון? ${ic('arrow',16)}</a></section></div>
  <div class="platform-strip"><span>ליווי בעולם שבו אנחנו חיים</span><b>Instagram</b><b>WhatsApp</b><b>Discord</b><b>Roblox</b><b>TikTok</b></div></div>`;
  document.getElementById('quick-report').onsubmit = e => {e.preventDefault(); sessionStorage.setItem('smai_report_draft', document.getElementById('quick-description').value); location.hash = '#/report';};
}
